Resources:
  VideoCloudDB:
    Type: 'AWS::RDS::DBInstance'
    Properties: 
      AllocatedStorage: '5'
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: videocloud
      Engine: postgres
      DBName: ${self:custom.secrets.DB_NAME}
      MasterUsername: ${self:custom.secrets.DB_USER}
      MasterUserPassword: ${self:custom.secrets.DB_PASS}

